services:
  db:
    image: postgis/postgis:16-3.4
    container_name: pedivoy_db
    environment:
      POSTGRES_DB: pedivoy
      POSTGRES_USER: pedivoy
      POSTGRES_PASSWORD: pedivoy
    ports:
      - "5432:5432"
    volumes:
      - pedivoy_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedivoy -d pedivoy"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pedivoy_pgdata:
